name: Deploy
on:
  push:
    branches:
    - master
    - deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ i686, x86_64 ]
        build_type: [ release, debug ]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Add safe git directory
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          file: ./dockerfiles/${{matrix.arch}}-w64-mingw32-shared-${{matrix.build_type}}.Dockerfile
          push: true
          tags: jonaski/strawberry-mxe-${{matrix.arch}}-${{matrix.build_type}}:latest
